CREATE TABLE PROPIETARIO
(
  ID_PROPIETARIO  NUMBER(10)                    NOT NULL,
  DOMICILIO       VARCHAR2(50 BYTE),
  TELEFONO        VARCHAR2(20 BYTE),
  EMAIL           VARCHAR2(50 BYTE),
  TIPO            VARCHAR2(10 BYTE)             NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROPIETARIO_EMPRESA
(
  ID_PROPIETARIO              NUMBER(10)        NOT NULL,
  CUIT                        VARCHAR2(20 BYTE) NOT NULL,
  RAZON_SOCIAL                VARCHAR2(100 BYTE),
  FECHA_COMIENZO_ACTIVIDADES  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROPIETARIO_PARTICULAR
(
  ID_PROPIETARIO  NUMBER(10)                    NOT NULL,
  APELLIDO        VARCHAR2(50 BYTE),
  NOMBRE          VARCHAR2(20 BYTE),
  DOCUMENTO       NUMBER(20)                    NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ZONA
(
  ID_ZONA      NUMBER(10)                       NOT NULL,
  DESCRIPCION  VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIPO_INMUEBLE
(
  ID_TIPO_INMUEBLE  NUMBER(10)                  NOT NULL,
  DESCRIPCION       VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIPO_GASTO
(
  ID_TIPO_GASTO  NUMBER(10)                     NOT NULL,
  DESCRIPCION    VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TEXTO
(
  ID_TEXTO     NUMBER(10)                       NOT NULL,
  DESCRIPCION  VARCHAR2(4000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTRATO_ALQUILER
(
  ID_CONTRATO       NUMBER(10)                  NOT NULL,
  IMPORTE_ACORDADO  NUMBER(8)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTRATO_VENTA
(
  ID_CONTRATO            NUMBER(10)             NOT NULL,
  COMISION_INMOBILIARIA  NUMBER(8),
  PRECIO_INICIAL_VENTA   NUMBER(8),
  PRECIO_MINIMO          NUMBER(8),
  CONDICIONES_VISITA     VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE VENDEDOR
(
  ID_VENDEDOR     NUMBER(10)                    NOT NULL,
  APELLIDO        VARCHAR2(50 BYTE),
  DOMICILIO       VARCHAR2(50 BYTE),
  TELEFONO        VARCHAR2(20 BYTE),
  EMAIL           VARCHAR2(50 BYTE),
  FECHA_COMIENZO  DATE,
  EXPERIENCIA     VARCHAR2(2000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE COMPRADOR
(
  ID_COMPRADOR  NUMBER(10)                      NOT NULL,
  APELLIDO      VARCHAR2(50 BYTE),
  NOMBRE        VARCHAR2(20 BYTE),
  DOMICILIO     VARCHAR2(50 BYTE),
  TELEFONO      VARCHAR2(20 BYTE),
  EMAIL         VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX COMPRADOR_PK ON COMPRADOR
(ID_COMPRADOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONTRATO_ALQUILER_PK ON CONTRATO_ALQUILER
(ID_CONTRATO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CONTRATO_VENTA_PK ON CONTRATO_VENTA
(ID_CONTRATO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PROPIETARIO_PK ON PROPIETARIO
(ID_PROPIETARIO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PROPIETARIO_EMPRESA_PK ON PROPIETARIO_EMPRESA
(ID_PROPIETARIO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PROPIETARIO_PARTICULAR_PK ON PROPIETARIO_PARTICULAR
(ID_PROPIETARIO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PROPIETARIO_PARTICULAR_U01 ON PROPIETARIO_PARTICULAR
(DOCUMENTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TEXTO_PK ON TEXTO
(ID_TEXTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TIPO_GASTO_PK ON TIPO_GASTO
(ID_TIPO_GASTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TIPO_INMUEBLE_PK ON TIPO_INMUEBLE
(ID_TIPO_INMUEBLE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX VENDEDOR_PK ON VENDEDOR
(ID_VENDEDOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ZONA_PK ON ZONA
(ID_ZONA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE TABLE INMUEBLE
(
  ID_INMUEBLE         NUMBER(10)                NOT NULL,
  ID_PROPIETARIO      NUMBER(10)                NOT NULL,
  DIRECCION           VARCHAR2(50 BYTE),
  ESTADO              VARCHAR2(50 BYTE),
  ANTIGUEDAD          NUMBER(2),
  PLANO               VARCHAR2(50 BYTE),
  METROS_CUADRADOS    NUMBER(4),
  ORIENTACION         VARCHAR2(5 BYTE),
  CANTIDAD_AMBIENTES  NUMBER(1),
  FECHA_FINALIZACION  DATE,
  ID_ZONA             NUMBER(10)                NOT NULL,
  ID_TIPO_INMUEBLE    NUMBER(10)                NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FOTO_INMUEBLE
(
  ID_FOTO_INMUEBLE  NUMBER(10)                  NOT NULL,
  ID_INMUEBLE       NUMBER(10)                  NOT NULL,
  FOTO_REAL         BLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (FOTO_REAL) STORE AS 
      ( TABLESPACE  USERS 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE USERS
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE GASTO_INMUEBLE
(
  ID_GASTO_INMUEBLE  NUMBER(10)                 NOT NULL,
  ID_INMUEBLE        NUMBER(10)                 NOT NULL,
  VALOR              NUMBER(5),
  ID_TIPO_GASTO      NUMBER(10)                 NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTRATO
(
  ID_CONTRATO      NUMBER(10)                   NOT NULL,
  ID_INMUEBLE      NUMBER(10)                   NOT NULL,
  FECHA_FIRMA      DATE,
  VIGENCIA_INICIO  DATE,
  VIGENCIA_FIN     DATE,
  TIPO_CONTRATO    VARCHAR2(8 BYTE)             NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MODIFICACION
(
  ID_CONTRATO   NUMBER(10)                      NOT NULL,
  ID_TEXTO      NUMBER(10)                      NOT NULL,
  FECHA_INICIO  DATE,
  FECHA_FIN     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIENE_ASIGNADO
(
  ID_VENDEDOR        NUMBER(10)                 NOT NULL,
  ID_CONTRATO        NUMBER(10)                 NOT NULL,
  ID_COMPRADOR       NUMBER(10),
  FECHA_COMPRA       DATE,
  COMISION_VENDEDOR  NUMBER(8),
  IMPORTE_DE_VENTA   NUMBER(8)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SE_LO_MOSTRO
(
  ID_COMPRADOR      NUMBER(10)                  NOT NULL,
  ID_VENDEDOR       NUMBER(10)                  NOT NULL,
  ID_CONTRATO       NUMBER(10)                  NOT NULL,
  FECHA_DE_MUESTRA  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CONTRATO_PK ON CONTRATO
(ID_CONTRATO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FOTO_INMUEBLE_PK ON FOTO_INMUEBLE
(ID_FOTO_INMUEBLE, ID_INMUEBLE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX GASTO_INMUEBLE_PK ON GASTO_INMUEBLE
(ID_GASTO_INMUEBLE, ID_INMUEBLE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INMUEBLE_PK ON INMUEBLE
(ID_INMUEBLE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MODIFICACION_PK ON MODIFICACION
(ID_CONTRATO, ID_TEXTO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SE_LO_MOSTRO_PK ON SE_LO_MOSTRO
(ID_COMPRADOR, ID_VENDEDOR, ID_CONTRATO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX TIENE_ASIGNADO_PK ON TIENE_ASIGNADO
(ID_VENDEDOR, ID_CONTRATO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER TIENE_ASIGNADO_TRG
BEFORE INSERT OR UPDATE
ON TIENE_ASIGNADO 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
    vEXCEPTION  EXCEPTION;
    vERROR      NUMBER;
BEGIN
    vERROR := -20001;       
    IF (:NEW.ID_COMPRADOR IS NOT NULL AND :NEW.FECHA_COMPRA IS NOT NULL AND :NEW.COMISION_VENDEDOR IS NOT NULL AND :NEW.IMPORTE_DE_VENTA IS NOT NULL) THEN
        vERROR := 0;
    END IF; 
    IF (:NEW.ID_COMPRADOR IS NULL AND :NEW.FECHA_COMPRA IS NULL AND :NEW.COMISION_VENDEDOR IS NULL AND :NEW.IMPORTE_DE_VENTA IS NULL) THEN
        vERROR := 0;
    END IF; 
    IF (vERROR != 0) THEN
        RAISE vEXCEPTION;
    END IF;
    
   EXCEPTION
     WHEN vEXCEPTION THEN
       -- Consider logging the error and then re-raise
       RAISE_APPLICATION_ERROR(vERROR, 'Los campos asociados a la venta tienen que ser todos nulos o no nulos.');
END ;
/


CREATE OR REPLACE TRIGGER SE_LO_MOSTRO_TRG
BEFORE INSERT OR UPDATE
ON SE_LO_MOSTRO 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
    vEXCEPTION      EXCEPTION;
    vCANTIDAD       NUMBER;
BEGIN
    SELECT COUNT(*) INTO vCANTIDAD
        FROM TIENE_ASIGNADO TA
        WHERE TA.ID_CONTRATO = :NEW.ID_CONTRATO
            AND TA.ID_VENDEDOR = :NEW.ID_VENDEDOR;

    IF (vCANTIDAD = 0) THEN    
        RAISE vEXCEPTION;
    END IF;
   EXCEPTION
     WHEN vEXCEPTION THEN
       RAISE_APPLICATION_ERROR(-20001, 'Solo se puede mostrar un contrato que el vendedor tiene asignado.');
END SE_LO_MOSTRO_TRG;
/


ALTER TABLE PROPIETARIO ADD (
  CONSTRAINT CHECK_TIPO
 CHECK (tipo IN ('Empresa','Particular')),
  CONSTRAINT PROPIETARIO_PK
 PRIMARY KEY
 (ID_PROPIETARIO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE PROPIETARIO_EMPRESA ADD (
  CONSTRAINT PROPIETARIO_EMPRESA_PK
 PRIMARY KEY
 (ID_PROPIETARIO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE PROPIETARIO_PARTICULAR ADD (
  CONSTRAINT PROPIETARIO_PARTICULAR_PK
 PRIMARY KEY
 (ID_PROPIETARIO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT PROPIETARIO_PARTICULAR_U01
 UNIQUE (DOCUMENTO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ZONA ADD (
  CONSTRAINT ZONA_PK
 PRIMARY KEY
 (ID_ZONA)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE TIPO_INMUEBLE ADD (
  CONSTRAINT TIPO_INMUEBLE_PK
 PRIMARY KEY
 (ID_TIPO_INMUEBLE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE TIPO_GASTO ADD (
  CONSTRAINT TIPO_GASTO_PK
 PRIMARY KEY
 (ID_TIPO_GASTO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE TEXTO ADD (
  CONSTRAINT TEXTO_PK
 PRIMARY KEY
 (ID_TEXTO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE CONTRATO_ALQUILER ADD (
  CONSTRAINT CONTRATO_ALQUILER_PK
 PRIMARY KEY
 (ID_CONTRATO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE CONTRATO_VENTA ADD (
  CONSTRAINT PRECIOMIN_MAYOR_A_0
 CHECK (PRECIO_MINIMO > 0),
  CONSTRAINT PRECIOVENTA_MAYOR_A_PRECIOMIN
 CHECK (PRECIO_MINIMO <= PRECIO_INICIAL_VENTA),
  CONSTRAINT CONTRATO_VENTA_PK
 PRIMARY KEY
 (ID_CONTRATO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE VENDEDOR ADD (
  CONSTRAINT VENDEDOR_PK
 PRIMARY KEY
 (ID_VENDEDOR)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE COMPRADOR ADD (
  CONSTRAINT COMPRADOR_PK
 PRIMARY KEY
 (ID_COMPRADOR)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE INMUEBLE ADD (
  CONSTRAINT INMUEBLE_PK
 PRIMARY KEY
 (ID_INMUEBLE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FOTO_INMUEBLE ADD (
  CONSTRAINT FOTO_INMUEBLE_PK
 PRIMARY KEY
 (ID_FOTO_INMUEBLE, ID_INMUEBLE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE GASTO_INMUEBLE ADD (
  CONSTRAINT GASTO_INMUEBLE_PK
 PRIMARY KEY
 (ID_GASTO_INMUEBLE, ID_INMUEBLE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE CONTRATO ADD (
  CONSTRAINT CHECK_FECHA_FIRMA_CONTRATO
 CHECK (FECHA_FIRMA <= VIGENCIA_INICIO),
  CONSTRAINT CHECK_VIGENCIA_CONTRATO
 CHECK (VIGENCIA_INICIO < VIGENCIA_FIN),
  CONSTRAINT CHECK_TIPOCONTRATO
 CHECK (tipo_contrato IN ('Venta','Alquiler')),
  CONSTRAINT CONTRATO_PK
 PRIMARY KEY
 (ID_CONTRATO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE MODIFICACION ADD (
  CONSTRAINT MODIFICACION_PK
 PRIMARY KEY
 (ID_CONTRATO, ID_TEXTO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE TIENE_ASIGNADO ADD (
  CONSTRAINT TIENE_ASIGNADO_PK
 PRIMARY KEY
 (ID_VENDEDOR, ID_CONTRATO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SE_LO_MOSTRO ADD (
  CONSTRAINT SE_LO_MOSTRO_PK
 PRIMARY KEY
 (ID_COMPRADOR, ID_VENDEDOR, ID_CONTRATO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE PROPIETARIO_EMPRESA ADD (
  CONSTRAINT PROPIETARIOE_PROPIETARIO_FK 
 FOREIGN KEY (ID_PROPIETARIO) 
 REFERENCES PROPIETARIO (ID_PROPIETARIO));

ALTER TABLE PROPIETARIO_PARTICULAR ADD (
  CONSTRAINT PROPIETARIOP_PROPIETARIO_FK 
 FOREIGN KEY (ID_PROPIETARIO) 
 REFERENCES PROPIETARIO (ID_PROPIETARIO));

ALTER TABLE INMUEBLE ADD (
  CONSTRAINT INMUEBLE_PROPIETARIO_FK 
 FOREIGN KEY (ID_PROPIETARIO) 
 REFERENCES PROPIETARIO (ID_PROPIETARIO),
  CONSTRAINT INMUEBLE_ZONA_FK 
 FOREIGN KEY (ID_ZONA) 
 REFERENCES ZONA (ID_ZONA),
  CONSTRAINT INMUEBLE_TIPOINMUEBLE_FK 
 FOREIGN KEY (ID_TIPO_INMUEBLE) 
 REFERENCES TIPO_INMUEBLE (ID_TIPO_INMUEBLE));

ALTER TABLE FOTO_INMUEBLE ADD (
  CONSTRAINT FOTOINMUEBLE_INMUEBLE_FK 
 FOREIGN KEY (ID_INMUEBLE) 
 REFERENCES INMUEBLE (ID_INMUEBLE));

ALTER TABLE GASTO_INMUEBLE ADD (
  CONSTRAINT GASTOINMUEBLE_INMUEBLE_FK 
 FOREIGN KEY (ID_INMUEBLE) 
 REFERENCES INMUEBLE (ID_INMUEBLE),
  CONSTRAINT GASTOINMUEBLE_TIPOGASTO_FK 
 FOREIGN KEY (ID_TIPO_GASTO) 
 REFERENCES TIPO_GASTO (ID_TIPO_GASTO));

ALTER TABLE CONTRATO ADD (
  CONSTRAINT CONTRATO_INMUEBLE_FK 
 FOREIGN KEY (ID_INMUEBLE) 
 REFERENCES INMUEBLE (ID_INMUEBLE));

ALTER TABLE MODIFICACION ADD (
  CONSTRAINT MODIFICACION_CONTRATO_FK 
 FOREIGN KEY (ID_CONTRATO) 
 REFERENCES CONTRATO (ID_CONTRATO),
  CONSTRAINT MODIFICACION_TEXTO_FK 
 FOREIGN KEY (ID_TEXTO) 
 REFERENCES TEXTO (ID_TEXTO));

ALTER TABLE TIENE_ASIGNADO ADD (
  CONSTRAINT TIENEASIGNADO_VENDEDOR_FK 
 FOREIGN KEY (ID_VENDEDOR) 
 REFERENCES VENDEDOR (ID_VENDEDOR),
  CONSTRAINT TIENEASIGNADO_CONTRATO_FK 
 FOREIGN KEY (ID_CONTRATO) 
 REFERENCES CONTRATO_VENTA (ID_CONTRATO),
  CONSTRAINT TIENEASIGNADO_COMPRADOR_FK 
 FOREIGN KEY (ID_COMPRADOR) 
 REFERENCES COMPRADOR (ID_COMPRADOR));

ALTER TABLE SE_LO_MOSTRO ADD (
  CONSTRAINT SELOMOSTRO_VENDEDOR_FK 
 FOREIGN KEY (ID_VENDEDOR) 
 REFERENCES VENDEDOR (ID_VENDEDOR),
  CONSTRAINT SELOMOSTRO_CONTRATO_FK 
 FOREIGN KEY (ID_CONTRATO) 
 REFERENCES CONTRATO (ID_CONTRATO),
  CONSTRAINT SELOMOSTRO_COMPRADOR_FK 
 FOREIGN KEY (ID_COMPRADOR) 
 REFERENCES COMPRADOR (ID_COMPRADOR));

